[package]
name = "git-identity"
version = "0.1.0"
authors = ["simon <s.r.walker101@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.12"
anyhow = "1.0.28"
dirs = "2.0.2"
